sudo: required
language: python
env:
  global:
  - secure: SbrMnpKPD3dDydaEg0law5NzLHO4YaK2akKFPSExF8k9gF4Ggf2poY+Cq9wUVTAekfQC6SOrQ9slN/WuKeOV4VS1uc49zA0aSvi+liLNarvTOJKa+dQaK4ZwTYrccJH44ANsdfHZt72y9Lc8mlCWHeKlSDLkU1nwXifXaB/CWxM0nxLF7sav9nh/DQbR4BOOoUEH6mokhcELxINGWXphXSP/x0bY2IGr+VxFfVMkHKbGWrmrxEVRsc8FLQdFTaH2dscSSGWr2ThH95stGKEs+2ppgv6utsuoCMOI+0n7Y+ctcnhWOf2XNMOaHmWNuBpLqVLf3jhdBajln6l8FfXHOzA5tkH+CwoWlVaCn1YIjkWuV2jJ4/crMuxL3d3Rgf/Twyl2+HwP3h8Ck9criBLLsTwu2OhwWG4XNYXHsfM3Z2GIwVCmAbxQ2SkBFJq3B9lwC9e8a/+gd0Aj9abvib5s31oX5es9jqQd2j39q76fVnprGXHHF3swAK1+mhUhC8lBcE30bost9kekRmhi0XU6G5OCIHv5e0R67Rh9zu58pU9lIISvrK6kNOHu3n0g573Rj/OVIC8ZgR/Y6qm1SiNFibPhetJG/DbAZqtjaTCxS8Bne8AgorIIfhpMVj/cnAD0gOz+3WWDgbecoH8UwHg51aCy3eoihn8vc6UCVLqeA6s=
  - secure: jCPgaUnLnfuU9r+d9Dw0/rZfjrFEE0jg1EPKEqBZxKZAdrkZCE1WxMqNifHiRHcYJeyhZ6z8+/j9ZPe1+3pCpU2vbBipGXdOG9pM3BtvVv9CKKS5n9tQkuToNHM0GdOHEISFsglPD37hQjeV4i640tzwagEj/gcxC14wVVeoyAKK7UyNt/V+M20d33MOscLmMO6MkW36WPyRkd989mbvyUtyKaqWkcHqgvq0t/df41YDKU15fZ6T9Pi5uWn9HBMll6F09QPK9G0uuvBtKmof+PL9IuR2g4vdYcNYgVGKog92GGC2xXKss4gAWqjdWG40ByNvC23LTefV7bJTtLMbtemv+GaXQ1qh/is6z0VQ+Zs8gPI6GlCa9ydaHzmuF9FNd6z748S3b2OoOr/jcwuC6u/jrmfTgqBhPYhhai1oWN9UMWG7TBPfJER3YIlPns0GTN4klSxnPZhzZoYLFor3NtShU5iqDgXVpwcoLhCLzv6UNsCvX+T3fVSd2nOOyWAUzOI4dkUhiDCqV57d6EC/u3nh3zHYKYrCq6e5Ik3yZZB0VDe3jnKxsAKP0kySfhC8OFM2OTHFBY5n3i0ITaZwfZ3tER6ShQ38vHLkwTsa7G/JusRqcPpFpfLga7EjLmU9fwrmR8Eu9+8iEel7eK/Eg1ouQ1nouIlT5zC2HEB2f94=
  - secure: lQ2xi5K7RKOna5OJAMIRhO502Dw3ZBYneKJaQ4OKVl7/Eex0+T81/urvkjUdVlMHSqwFjZJdqG3epNiZLcI8Sw/nHMzSymaBL+SL8fJ2FTQuG3OI0MzKQc5IPJ/wxq1Iqpo7dxH6gbasXSW9QueX07d1U0c71s/L6/Pfp1nbi6qsZQiyaNX6MR5XDtHbqXiN/x3qohHrjjFEuMbMR6vXXc+KF9JW/euMGIW/HaXmE/i8RnDcNS3Z1zJEr5yfVvrTZFWSfxCbwfkDeVD7TlP6Jm1gFsN3Obf1UhhA6FKeZ2/H8kebDk2iDghjhddWVD6uCK95Y62+XLe2/2e8Fkbtc8vnoyHXPxftCqF2zG9dg8Blv162JJimy53SI9N1chM/ivq8ErX8i2iGSF+Os0rCG0Y3roaqN7BseDD8/ouwmY20PQrO03VPSdI9rL2Hi1zBNMx3NCNDNar+x/ax8LXlJpvyZcesfAL/nF4RpKA/A5PUolBbV3h4nDzQQfYC/d0f6tLx9RrDfb69yLIYu1yFMa9+sAr21Bnq4j15v8KdYBPSQ8XYu6lkqGK5P77D4+gvup6HhGBxm+fmyeFvNXbQa0jJcrBNM/n9ALw7yvp9ARRSE/7VraSGjgi3xn9/z9uIm5+Wg+yQmtb9SE60EWQcGcd7KcxJawxrpB8pbMi7moA=
services:
- docker
before_install:
- pip install docker-compose
script:
- docker-compose build
- docker-compose up -d
- docker exec exemplofluxodocker_flapp_webapp_1 make test
- docker run -it --net host --pid host --cap-add audit_control -v /var/lib:/var/lib
  -v /var/run/docker.sock:/var/run/docker.sock -v /usr/lib/systemd:/usr/lib/systemd
  -v /etc:/etc --label docker_bench_security docker/docker-bench-security
after_success:
- echo $DOCKER_USER
- docker login -u=$DOCKER_USER -p=$DOCKER_PASS
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" == "push" ]; then
  docker build -t $TRAVIS_REPO_SLUG .; docker push $TRAVIS_REPO_SLUG; fi
