sudo: required

language: python

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

services:
  - docker

before_install:
  - pip install docker-compose

script:
  - make travis_compose_build
  - make travis_compose_up
  - make travis_compose_make_test
  - make travis_run_audit

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" == "push" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
    make release_docker_build;
    make release_docker_tag;
    make release_docker_push;
    docker login -u="$REGISTRY_SCIELO_USER" -p="$REGISTRY_SCIELO_PASS" $REGISTRY_SCIELO;
    make release_scielo_tag;
    make release_docker_push;
    fi
