sudo: required
language: python
env:
  global:
    - secure: J1z6tVHmq+pidEaYfNUpwg8WBvAP/9atQBXJOL39OUGZD4trt6kejOLy7sW5HfZoJHTxKPSdVD5CYLaaRebPPbM1vXClHJE0u3l4rCpuMFuSQ/4J2env/st6P4cgcY4kPd9q9jqA7v3kDGBuoqDfXzKGMVm/zPyH36eUVlz9p/OhBeV9ZKtxAP9QdV0tOHiCfnkebLvHBsfvIKYud55Dpwq9bD6R5Tu+8lIjas/DfbWdA1kvYmtN2Uni4bchYEQnLD1s+USvEPj9UN5qNQhufT/0ZQVED8i5KqFndarb4t22tQNNei5kyOWvYjeaYpoIJVggHK3jL7MMHQmhsdtBXbCSD0D6NFGUzkVVMWZrzleMuowGXtHko6TWbPNIWaZrTiCcGYzCNJ7nUiuTNTDORjnpSC6/2JOXU8N1CXeOpKAWv+JkATvN1lJfhPLtq35XnpqOER/DF/OnNAlQDUzt5+m24OU6Hwl5/ylihiGoBclWzZkmxVhrAmxP+vuXDkVl8anYl/hszOhWzv9YotVGGPNn+faSysp7zgfEzf8oKgKIsDBAapSUzYH/sElnSK3NSv5sasLFReUIflcO7wtX5wuUEotbmfCfNoWWG4xIz3cocE2y5ytNsOW49cBPLBwdR3UqE2IqITDGaGGBZEkoa24MTCl+go3D189RkzrFIPo=
    - secure: MQUHf7F8AdVMm2ZwKPklQ/o5WfAT10CP05//pfGptmgkrNgZvlo00Lzar0Jj4aqyFNkJKuUiJzBazHozk9MY4vIo4gOUaIlPsLLJPl4Yl2n/7TeRy5BxyiJ/ZtoejYCWbWADqhuX/fN5HTh92f21slEZsshQouJctaUBajaI1RfThhACaFANDSYsFZk8ANla2W3kAUP9Ll8DOwnlgRsMCEKXIzj+4mugCDrRxFnGoo/9hgJQz1HI0ygqCnse89NmgUjoEosD0LJuLy755Uy01091h8FTW6Sm/Ly4EUr0fBB+4vCJXuy42yAB1Glw4JJlipEC9ApGJYe305GZYPIErhbL19Df9Sp+U1ffSJcOuBtJLvad/+YRDc69JfjUUuF0f1PV6n883cjwsbNSOWjUVXt3DEGuX72dh172ULZlXEAwGY3KvrW75L8RHoezNZiDK3DZgmEhXi0KYY/Zb89XGLmjLs3MWvV06Sn3mPiwGTeow7xkXMDToAaOjLTp6xPhinTSuqfKEi6xAQWaxHXqwT0O7D8DiCukkE4XCtZ48yKYHTJ6N9NR4MxFQl8pd2linDruU99JsU5FkRX2XyJvRW4PjgVMsgYH5XRlKweufUuiS6PpHQ9vsY/3YSpMtYRYpzO42UgVlmZckVJsvk0UMwiLYsm+zbAk9vpRf/2UIeE=
services:
- docker
before_install:
- pip install docker-compose
script:
- docker-compose build
- docker-compose up -d
- docker exec exemplofluxodocker_flapp_webapp_1 make test
- docker run -it --net host --pid host --cap-add audit_control -v /var/lib:/var/lib
  -v /var/run/docker.sock:/var/run/docker.sock -v /usr/lib/systemd:/usr/lib/systemd
  -v /etc:/etc --label docker_bench_security docker/docker-bench-security
after_success:
- echo $DOCKER_USER
- docker login -u=$DOCKER_USER -p=$DOCKER_PASS
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" == "push" ]; then
  docker build -t $TRAVIS_REPO_SLUG .; docker push $TRAVIS_REPO_SLUG; fi
