sudo: required

language: python

services:
  - docker

before_install:
  - pip install docker-compose

script:
  - docker-compose build
  - docker-compose up -d
  - docker exec exemplofluxodocker_flapp_webapp_1 make test
  - docker run -it --net host --pid host --cap-add audit_control -v /var/lib:/var/lib -v /var/run/docker.sock:/var/run/docker.sock -v /usr/lib/systemd:/usr/lib/systemd -v /etc:/etc --label docker_bench_security docker/docker-bench-security

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" == "push" ]; then
    docker build -t $TRAVIS_REPO_SLUG .;
    docker push $TRAVIS_REPO_SLUG;
    fi
